# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  schedule:
    # First of every month
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 1 * *'

permissions:
  contents: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build API
        run:
          bash monthly.sh
        uses: actions/deploy-pages@v2
      - name: Commit Monthly Data
        run: |
          git config --global user.name 'Hexylena'
          git config --global user.email 'hexylena@galaxians.org'
          git add monthly/
          git commit -am "Collecting monhtly numbers"
          git push
